/* qrmint.net service worker. GENERATED by tools/build_sw.py. Do not edit.
   Run `python3 tools/build_sw.py` to rewrite it after any page or asset
   change. `python3 tools/build_sw.py --check` reports a stale file. */

const VERSION = "70902ad9aba8";
const CACHE = "qrmint-" + VERSION;
const PRECACHE = [
  "/",
  "/wifi-qr-code/",
  "/vcard-qr-code/",
  "/email-qr-code/",
  "/sms-qr-code/",
  "/whatsapp-qr-code/",
  "/location-qr-code/",
  "/phone-number-qr-code/",
  "/scan-qr-code/",
  "/qr-code-labels/",
  "/bulk-qr-codes/",
  "/articles/",
  "/articles/how-qr-codes-work.html",
  "/articles/qr-code-error-correction-levels-explained.html",
  "/articles/how-to-share-wifi-with-a-qr-code.html",
  "/articles/qr-code-design-tips-that-still-scan.html",
  "/privacy/",
  "/terms/",
  "/assets/css/styles.css?v=3",
  "/assets/js/nav.js?v=4",
  "/assets/js/qrcodegen.js?v=3",
  "/assets/js/zipwriter.js?v=3",
  "/assets/js/app.js?v=3",
  "/assets/js/decode.js?v=3",
  "/assets/js/batch.js?v=3",
  "/assets/css/styles.css?v=4",
  "/assets/js/print.js?v=1",
  "/assets/js/jsqr.js",
];

// Install: fill the new cache from the network, not from the HTTP cache.
// `cache: "reload"` stops the browser cache from serving stale bytes.
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) =>
        cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "reload" })))
      )
      .then(() => self.skipWaiting())
  );
});

// Activate: delete every older cache of this site, then take control.
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith("qrmint-") && key !== CACHE)
            .map((key) => caches.delete(key))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);

  // Handle only same-origin GET requests. Return here for every other
  // request, with no call to respondWith. The AdSense script and every other
  // third-party request go straight to the network. The worker never
  // intercepts them and never caches them.
  if (request.method !== "GET" || url.origin !== self.location.origin) {
    return;
  }

  // Cache first. The precache is the whole offline set. The worker never
  // writes a network response into the cache. A new deploy gets a new cache
  // name, and that is the only invalidation.
  event.respondWith(
    caches.match(request, { ignoreSearch: false }).then((hit) => {
      if (hit) return hit;
      if (request.mode !== "navigate") return fetch(request);
      return caches.match(url.pathname).then((page) => {
        if (page) return page;
        if (!url.pathname.endsWith("/")) return fetch(request);
        return caches
          .match(url.pathname + "index.html")
          .then((index) => index || fetch(request));
      });
    })
  );
});
