#!/usr/bin/env python3
"""Write sw.js, the service worker that makes the site load offline.

Stdlib only. The precache list is not hand-typed. This script reads the page
list from sitemap.xml and then scans each page for the same-origin CSS and JS
files that it loads, with the `?v=` query kept exactly as written.

    python3 tools/build_sw.py          # rewrite sw.js
    python3 tools/build_sw.py --check  # exit 1 if sw.js is stale

The cache name is "qrmint-" plus a content hash. The hash covers the bytes of
every precached file, so any change to a page or an asset gives the worker a
new cache name. The browser then installs the new worker, fills the new cache
and deletes the old one. Run this script before every deploy.
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parent.parent
SITE = "qrmint"
SITEMAP = ROOT / "sitemap.xml"
OUT = ROOT / "sw.js"

# Same-origin scripts that a page loads at run time with `s.src = ...`, not
# with a <script> tag. The HTML scan cannot see them. Each entry must exist.
DYNAMIC_SCRIPTS = ["/assets/js/jsqr.js"]

LINK_RE = re.compile(r'<link\b[^>]*\brel="stylesheet"[^>]*\bhref="([^"]+)"', re.I)
SCRIPT_RE = re.compile(r'<script\b[^>]*\bsrc="([^"]+)"', re.I)

TEMPLATE = """\
/* qrmint.net service worker. GENERATED by tools/build_sw.py. Do not edit.
   Run `python3 tools/build_sw.py` to rewrite it after any page or asset
   change. `python3 tools/build_sw.py --check` reports a stale file. */

const VERSION = "%(version)s";
const CACHE = "%(site)s-" + VERSION;
const PRECACHE = [
%(precache)s
];

// Install: fill the new cache from the network, not from the HTTP cache.
// `cache: "reload"` stops the browser cache from serving stale bytes.
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) =>
        cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "reload" })))
      )
      .then(() => self.skipWaiting())
  );
});

// Activate: delete every older cache of this site, then take control.
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith("%(site)s-") && key !== CACHE)
            .map((key) => caches.delete(key))
        )
      )
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);

  // Handle only same-origin GET requests. Return here for every other
  // request, with no call to respondWith. The AdSense script and every other
  // third-party request go straight to the network. The worker never
  // intercepts them and never caches them.
  if (request.method !== "GET" || url.origin !== self.location.origin) {
    return;
  }

  // Cache first. The precache is the whole offline set. The worker never
  // writes a network response into the cache. A new deploy gets a new cache
  // name, and that is the only invalidation.
  event.respondWith(
    caches.match(request, { ignoreSearch: false }).then((hit) => {
      if (hit) return hit;
      if (request.mode !== "navigate") return fetch(request);
      return caches.match(url.pathname).then((page) => {
        if (page) return page;
        if (!url.pathname.endsWith("/")) return fetch(request);
        return caches
          .match(url.pathname + "index.html")
          .then((index) => index || fetch(request));
      });
    })
  );
});
"""


def sitemap_paths():
    """Every <loc> in sitemap.xml as a root-relative path."""
    text = SITEMAP.read_text(encoding="utf-8")
    locs = re.findall(r"<loc>\s*([^<\s]+)\s*</loc>", text)
    if not locs:
        raise SystemExit("no <loc> entries in %s" % SITEMAP)
    return [urlsplit(loc).path or "/" for loc in locs]


def file_for(path):
    """The file that the static server sends for a root-relative URL path."""
    bare = urlsplit(path).path
    if bare.endswith("/"):
        return ROOT / bare.lstrip("/") / "index.html"
    return ROOT / bare.lstrip("/")


def same_origin(href):
    """True for a root-relative path. False for any URL with a scheme or host."""
    return href.startswith("/") and not href.startswith("//")


def page_assets(html):
    found = []
    for pattern in (LINK_RE, SCRIPT_RE):
        for href in pattern.findall(html):
            if same_origin(href) and href not in found:
                found.append(href)
    return found


def precache_list():
    pages = sitemap_paths()
    assets = []
    for path in pages:
        html = file_for(path).read_text(encoding="utf-8")
        for href in page_assets(html):
            if href not in assets:
                assets.append(href)
    for href in DYNAMIC_SCRIPTS:
        if href not in assets:
            assets.append(href)
    entries = pages + assets
    missing = [e for e in entries if not file_for(e).is_file()]
    if missing:
        raise SystemExit("precache entry has no file: %s" % ", ".join(missing))
    return entries


def content_hash(entries):
    h = hashlib.sha256()
    for entry in entries:
        h.update(entry.encode("utf-8"))
        h.update(b"\0")
        h.update(file_for(entry).read_bytes())
        h.update(b"\0")
    return h.hexdigest()[:12]


def render():
    entries = precache_list()
    return TEMPLATE % {
        "site": SITE,
        "version": content_hash(entries),
        "precache": "\n".join('  "%s",' % e for e in entries),
    }, entries


def main():
    ap = argparse.ArgumentParser(description="Write the service worker.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if sw.js does not match the current files")
    args = ap.parse_args()

    text, entries = render()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if args.check:
        if text != current:
            print("sw.js is stale: run python3 tools/build_sw.py")
            return 1
        print("sw.js is current (%d precache entries)" % len(entries))
        return 0
    if text == current:
        print("sw.js unchanged (%d precache entries)" % len(entries))
        return 0
    OUT.write_text(text, encoding="utf-8")
    print("wrote sw.js (%d precache entries)" % len(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main())
